Dockerfile.dapper
Signed-off-by: Kiefer Chang <kiefer.chang@suse.com>
=> Bump Go to 1.16.7 and golangci-lint to v1.42.0

hack/collector-harvesteros, hack/collector-k3os, hack/support-bundle-collector.sh, package/Dockerfile, pkg/manager/agent.go, scripts/build, scripts/package
- Select os-collector based on OS ID. Now supports both k3os and harvesteros.
- Mount the whole host root directory into pod.
Signed-off-by: Kiefer Chang <kiefer.chang@suse.com>
=> Add harvester os-collector

cmd/manager.go, pkg/manager/agent.go, pkg/manager/manager.go, pkg/types/types.go
Specify strings like `key1=value1,key2=value2` in `SUPPORT_BUNDLE_NODE_SELECTOR` env variable or `--node-selector` flag to ensure the agent DaemonSet pods are only run on certain nodes.
It's a short-term solution.
Ideally, we can have a similar match expression like SUC:
https://github.com/rancher/system-upgrade-controller/blob/32a31b23226239802348a4b7ab3dbfcb06f983e1/examples/k3s-upgrade.yaml#L38-L44
=> Support specifying nodeSelector of agent DaemonSet

pkg/manager/client/discovery.go, pkg/manager/cluster.go
- Increase the Burst and QPS values of DiscoveryClient (now defaults to 10000). The cluster resource collecting phase time is reduced from 3 mins to 23 secs in my cluster)
- The client code might specify a namespace that's already defined in our default ones (`"default", "kube-system", "cattle-system"`). Do not process a namespace twice if that's already processed.
Fix https://github.com/rancher/support-bundle-kit/issues/14.
References:
- The [Burst and QPS values adjusted in the discovery client](https://github.com/kubernetes/kubernetes/pull/86168/files#diff-14f541e7356b7bc7f735b24db888b48b81b81e136b5af2925e912b95889dd010) are not large enough for our use case.
- [Some implementations](https://github.com/voyagermesh/voyager/issues/640#issuecomment-337450743) increase the values up to …
=> Fix API throttling to speed up the bundle generation

pkg/manager/agent.go, pkg/manager/manager.go
We currently skip nodes with unavailable network and not ready kubelet. 
Nodes tainted with `node.kubernetes.io/unschedulable:NoSchedule` are tolerated.
Related issue: https://github.com/harvester/harvester/issues/1524
Any improvement is welcome.
=> Skip unreachable node during collecting NodeBundles

cmd/manager.go, pkg/manager/client/discovery.go, pkg/manager/cluster.go, pkg/manager/manager.go
Arg `--exclude-resources` (env `SUPPORT_BUNDLE_EXCLUDE_RESOURCES`)
accepts a comma-separated list of `<resource-name>.<group>` qualified
name of resources. Mainly serves to exclude matched resources out from
packaging into support bundle.
At this moment, only `secrets` resource is excluded by default.
=> Support excluding resources out from packaging into support bundle.

hack/collector-harvester, package/Dockerfile
Fix https://github.com/rancher/support-bundle-kit/issues/28.
Add configs under `/etc/rancher`:
```
➜  node1 pwd
/Users/kiefer/Downloads/supportbundle_a968c64f-604a-4bce-9ed1-d2bee6fe58fc_2022-01-12T16-03-41Z/nodes/node1
➜  node1 find configs
configs/etc
configs/etc/harvester-release.yaml
configs/etc/hostname
configs/etc/rancher
configs/etc/rancher/rke2
configs/etc/rancher/rke2/config.yaml.d
configs/etc/rancher/rke2/config.yaml.d/40-rancherd.yaml
configs/etc/rancher/rke2/config.yaml.d/50-rancher.yaml
configs/etc/rancher/rke2/config.yaml.d/90-harvester-server.yaml
configs/etc/rancher/rke2/config.yaml.d/90-harvester-agent.yaml
configs/etc/rancher/agent
configs/etc/rancher/agent/cattle-id
configs/etc/rancher/agent/config.yaml
configs/etc/rancher/rancherd …
```
=> Remove sensitive data in configs and collect rancher configs

pkg/manager/agent.go, pkg/types/types.go
This was observed when collecting supportbundle during a upgrade.
The taint prevents agent to be scheduled on the draining node:
```
- effect: NoSchedule
key: kubevirt.io/drain
value: draining
```
The change allows agent daemon set to be scheduled on draining nodes.
=> Fix not able schedule an agent to a draining node

.gitignore, pkg/manager/manager.go
Since zip.OpenReader returns a ReadCloser it is the users responsibility
to close this when no longer needed, otherwise the file handle will be 
leaked.
=> Fix leaking file handle

cmd/simulator.go, pkg/simulator/apiserver/apiserver.go, pkg/simulator/apiserver/apiserver_test.go, pkg/simulator/crd/crd_test.go, tests/integration/suite_test.go
The current [hardcoded service cluster IP](https://github.com/rancher/support-bundle-kit/blob/master/pkg/simulator/apiserver/apiserver.go#L44) range can cause services to fail to start when its cluster IP is not within the range.
```
time="2022-10-28T07:31:53Z" level=error msg="error during creation of resource metrics-server with gvr /v1, Resource=services" error="Service \"metrics-server\" is invalid: spec.clusterIPs: Invalid value: []string{\"10.43.157.71\"}: failed to allocated ip:10.43.157.71 with error:provided IP is not in the valid range. The range of valid IPs is 10.53.0.0/16"
```
Propose to use the service cluster IP from the support bundle for the API server cluster IP range.
https://github.com/longhorn/longhorn/issues/2759
=> fix(simulator): API server service cluster IP range

pkg/manager/agent.go
Propose to have Agent DaemonSet respecting all taints to avoid getting blocked in node bundle collection. Because in Longhorn, we cannot predict and have no control over the node taints.
https://github.com/longhorn/longhorn/issues/2759
=> fix(agent-daemonset): tolerate all taints

package/Dockerfile
Related issue: https://github.com/rancher/support-bundle-kit/issues/64
This is required for `kubectl cp` command.
=> Add tar to the packaged container image

cmd/manager.go, hack/collector-default, hack/collector-longhorn, hack/support-bundle-collector.sh, pkg/manager/agent.go, pkg/manager/manager.go
[Longhorn 5073](https://github.com/longhorn/longhorn/issues/5073)
Signed-off-by: Ray Chang <ray.chang@suse.com>
Add `collector-default` to collect cluster host information and log includes syslog, dmesg, kernel log and kubelet log
=> feat: add new parameter `SUPPORT_BUNDLE_COLLECTOR` to specify collector script to execute

hack/support-bundle-collector.sh
[Longhorn 5670](https://github.com/longhorn/longhorn/issues/5670)
Signed-off-by: Ray Chang <ray.chang@suse.com>
Add to check if the os distro. file exits, and continue to collect other information even exception happened. 
Below is the test result:
- rename the `/etc/os-release` to make the file not exits
- Success to use `collect-longhorn.sh` to collect infos and logs
- if using the old version of support-bundle-kit, the pod will stuck in "No such file or directory" exception
=> fix: add os distro fault tolerant in support bundle collector

cmd/manager.go, pkg/manager/agent.go, pkg/manager/manager.go, pkg/manager/manager_test.go, scripts/test
https://github.com/rancher/support-bundle-kit/issues/57
https://github.com/longhorn/longhorn/issues/5614
=> fix(agent): should respect taint-toleration

cmd/root.go, cmd/simulator.go, pkg/manager/agent.go, pkg/manager/client/discovery.go, pkg/manager/client/k8s.go, pkg/manager/cluster.go, pkg/manager/collectors/harvester.go, pkg/manager/httpserver.go, pkg/manager/manager.go, pkg/simulator/objects/apply.go, pkg/simulator/objects/blockdevices_test.go, pkg/simulator/objects/events_test.go, pkg/simulator/objects/ingress_test.go, pkg/simulator/objects/loadbalancers_test.go, pkg/simulator/objects/objects.go, pkg/simulator/objects/objects_test.go, pkg/simulator/objects/process_node_zips.go, pkg/simulator/objects/process_node_zips_test.go, pkg/simulator/objects/workload_test.go, pkg/types/types.go, tests/integration/loadbundle_test.go, tests/integration/suite_test.go
Ref https://github.com/rancher/support-bundle-kit/issues/57, https://github.com/longhorn/longhorn/issues/5614
=> fix(agent): tainted nodes should not be counted

pkg/manager/manager.go
Since we've moved the `m.refreshNodes` post DaemonSet creation. Hence should lock the expected nodes to ensure this gets refreshed first before proceeding to compare for completion.
Ref:
- https://github.com/rancher/support-bundle-kit/issues/57
- https://github.com/longhorn/longhorn/issues/5614
=> fix(agent): completed without expected nodes

pkg/manager/client/k8s.go, pkg/manager/cluster.go, pkg/simulator/kubelet/kubelet.go
We should generate previous logs if pods restarted. That would help to investigate issues with more information.
e.g.
If we have longhorn manager logs like the following:
```
harvester-node-0:/var/log/pods/longhorn-system_longhorn-manager-llpkl_ee9cee76-22fd-4988-a47d-7f408b7ab444/longhorn-manager # ls -al
-rw-r----- 1 root root   736805 Dec 13 20:52 0.log
-rw-r----- 1 root root 10485891 Dec 13 08:44 0.log.20221213-084430
-rw-r----- 1 root root  6376246 Dec 23 02:49 1.log
-rw-r----- 1 root root 10485786 Dec 19 19:38 1.log.20221219-193902
```
we only generate the longhorn-manager.log for the latest log (means 12/19 - 12/23).
Sometimes we may need the previous logs for debugging. With this PR we may get longhorn-manager.log.1 for the previous log (means 12/13 - 12/19).
Thanks!
=> Make the previous logs of pods work correctly

hack/collector-longhorn
~Fix 1: https://github.com/longhorn/longhorn/issues/6338
Including archived syslog files is significantly inflating the size of the support bundle and is meaningless. We will only gather the most recent log entries that are not too far ago from the incident.~
Fix 2: https://github.com/longhorn/longhorn/issues/6544
Currently, the support bundle only collects [syslog from /var/log/syslog](https://github.com/rancher/support-bundle-kit/blob/v0.0.26/hack/collector-longhorn#L27). Without collecting from /var/log/messages we are overlooking the syslog collection for some Longhorn-supported operating systems, such as SUSE.
=> fix: collector-longhorn

pkg/manager/client/discovery.go, pkg/manager/collectors/common.go, pkg/manager/collectors/harvester.go
issue:
https://github.com/rancher/support-bundle-kit/issues/78
Generating YAML files of almost all resources in all namespaces, most of them are nearly empty, increase the difficulty to look/search target object in the SB file.
local test result:
https://github.com/rancher/support-bundle-kit/issues/78#issuecomment-1714013380
After the fix, the `yamls` fold will strip such kind of empty file:
```
cat ./yamls/namespaced/harvester-system/rke.cattle.io/v1/rkecontrolplanes.yaml
apiVersion: v1
items: []
kind: List
metadata:
continue: "null"
resourceVersion: "39418564"
```
each yaml file will have at least 1 list item.
=> Fix SBK to eliminate empty YAML file

hack/collector-harvester, pkg/manager/agent.go
Based on this suggestion from issue https://github.com/harvester/harvester/issues/4427, I modify `collector-harvester` to collect `containerd.log`.
First of all, I read the README and wiki to understand what/how this repo works, and took a look at folder structure to notice there are docs, scripts, hack and pkg might be important.
Then I tried to deploy to obtain more information in local k3d. I encountered a service account problem which doesn't exist in my cluster. It's normal behavior because I didn't install a harvester in my cluster. So, I created a service account for support-bundle-kit and granted it access to the kubernetes API.
After deploying successfully, I could see the log of bundling log files, but I found an error message `more than one support bundle manager pods are …
=> feature(agent): add containerd log in harvester

cmd/manager.go, pkg/manager/cluster.go, pkg/manager/manager.go, pkg/manager/types.go
Because we fetch custom resource from local_state which we create by ourself, so we should fetch custom resource from kubernetes API. However, there is another manager uses support bundle kit in different api group.
We could fetch data from env which the manager will give when manager create support bundle manager. It would be easier than fetching k8s api by telling who owns this support bundle kit manager.
This will follow https://github.com/harvester/harvester/pull/4662 test plan to test.
https://github.com/harvester/harvester/issues/4630
=> fix(manager): fetch metadata from ENV

deploy/manifests/support-bundle-manager.yaml
According to https://github.com/rancher/support-bundle-kit/blob/master/pkg/manager/agent.go#L30, it uses these labels https://github.com/rancher/support-bundle-kit/blob/master/pkg/types/types.go#L18-L23 to check manager exists or not. So, we need to correct it.
Run `kubectl apply -f deploy/manifests/support-bundle-manager.yaml`. It would succeed to fetch node log.
=> fix: manifest typo

hack/collector-harvester
https://github.com/harvester/harvester/issues/3838
The image GC will cause some potential problems which https://github.com/harvester/harvester/issues/3838 describes, so it would be better for debugging if we could provide a image list the users used. So, we could use the list to double check whether environment missed essential images or not.
Run the host command to fetch image list. But, in this case, we can't use `/host/var/lib/rancher/rke2/bin` directly because of host volume mount and symbolic link problem. It causes the not found problem in this path `/host/var/lib/rancher/rke2/bin`. So, we need to use real bin path to execute command with `readlink` command.
Unless we directly mount host's `/var/lib/rancher/rke2/bin` when creating daemonset, but I think it would be better to …
=> feat: add ctr image list

pkg/manager/manager.go
When you create multiple support bundle at the same time, they're stuck for waiting daemonset condition until timeout.
In general, there is no such case which creates multiple support bundle at the same time, but there is still an issue for that case, so I think we need to fix it.
<details>
<summary>Click to toggle contents of testing yaml</summary>
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
labels:
app: support-bundle-manager
rancher/supportbundle: sample-01
name: supportbundle-manager-sample-01
namespace: harvester-system
spec:
replicas: 1
selector:
matchLabels:
app: support-bundle-manager
template:
metadata:
labels:
app: support-bundle-manager
rancher/supportbundle: sample-01
spec:
containers:
- args:
- /usr/bin/support-bundle-kit
- manager
env:
- name: …
```
=> fix: support bundle daemonset condition

hack/collector-harvester
By default, supportconfig collects too much system info and this might exceed the support bundle manager timeout. Reduce the features to minimum features and some selected ones.
**Related issue**
https://github.com/harvester/harvester/issues/5323
**Test plan**
- Build the code and push the container image to a repo. You can test with `bk201z/support-bundle-kit:wip-5323`
- Edit setting `support-bundle-image` with `kubectl edit settings.harvesterhci.io/support-bundle-image` and set the value to the published image, for example:
```
value: '{"repository":"bk201z/support-bundle-kit","tag":"wip-5323","imagePullPolicy":"Always"}'
```
- Collect a support bundle and it should work. Comparing to the default image, you should notice the time to generate a support bundle is reduced.
- Check the …
=> harvester-collector: reduce supportconfig features

package/Dockerfile, scripts/package
I tested following situations, all work:
- Mac M1 execute ./scripts/build && ./scripts/package
- Linux Laptop (amd64) execute ./scripts/build && ./scripts/package
- Github Action
- Local Github Action
- Image can be used in linux/amd64 and linux/arm64 (Tested Image: jk82421/support-bundle-kit:pull-test-ci-01)
Through this change, it can speed up the local development which run ./scripts/package without waiting multiple platform build, and the image is still usable in linux/amd64 and linux/arm64.
Related Issue: https://github.com/harvester/harvester/issues/5327
=> ci: simplify the script/package to speed up local development

.github/workflows/template-build.yml
I copied this from Drone config before, but I realized VERSION not used in Dockerfile.
BTW, because we changed it from `ARG ARCH` to `ENV ARCH` in Dockerfile due to using buildx which provides TARGETPLATFORM.
=> ci: remove useless build args

vendor/k8s.io/apimachinery/pkg/api/validation/objectmeta.go, vendor/k8s.io/apiserver/pkg/registry/rest/meta.go, vendor/k8s.io/kubernetes/pkg/registry/core/pod/strategy.go
PR reverses some of the vendoring changes from previous PR: https://github.com/rancher/support-bundle-kit/pull/111 to ensure original object timestamps and honoured and log streaming works.
=> fixed timestamps and broken logging

pkg/manager/cluster.go, pkg/manager/collectors/cluster.go, pkg/manager/collectors/default.go, pkg/manager/collectors/harvester.go
the collectors in certain scenarios do not report the actual error encountered when connecting to the apiserver.
the PR attempts to add more error info in the logs.
=> improve error reporting

cmd/manager.go, pkg/manager/manager.go
Sometime nodes spend too much time collecting logs, even forever. It makes users can't download support bundle kit.
Add collecting node timeout. When collecting node reach timeout, it will skip it instead of stuck. Then users are able download support bundle without waiting. But, in the situation, there is no node's logs in support bundle file.
For example, if A node is finished before timeout, but B node isn't finished. There is only A node's logs in support bundle file. So, we're still able to check something.
https://github.com/harvester/harvester/issues/1646
This is test case when collecting node reach out the timeout.
```
level=debug msg="Creating daemonset supportbundle-agent-bundle-1wrog with image jk82421/support-bundle-kit:v0.0.36.4"  
level=debug msg="Waiting for the creation of …
```
=> feat: add node timeout

Dockerfile.dapper, hack/collector-harvester
This PR mainly moves the supportconfig file to the specific folder to clarify it.
Related issue: https://github.com/harvester/harvester/issues/6016
=> move supportconfig to scc folder instead logs

hack/collector-harvester, hack/collector-longhorn, hack/common, package/Dockerfile
- Now we can get more accurate timestamp
Related issue: https://github.com/harvester/harvester/issues/6043
=> collector: improve the log time format

pkg/manager/client/discovery.go, pkg/manager/collectors/cluster.go, pkg/manager/collectors/default.go, pkg/manager/collectors/harvester.go
Fixes #99 with best-effort.
I can't actually manage to hit an error like the on from https://github.com/rancher/support-bundle-kit/issues/99#issue-2215521652 in my cluster. I tried mangling the `cluster-admin` ClusterRole to remove access to nonResourceURLs and removing the `system:discovery` ClusterRoleBinding in an attempt to stop support-bundle-manager from using the Kubernetes Discovery API. This DID result in a support bundle without YAML files, but did not trigger the `Unable to fetch cluster resources` message (in either a modified or unmodified support-bundle-kit). This means I cannot actually show the result of this PR in action. However, it should provide us additional debugging information if the YAML collection fails again like this in the future.
=> Log underlying error when YAML generation fails

go.mod, go.sum, pkg/manager/manager.go, pkg/types/types.go, pkg/utils/prometheus.go, vendor/github.com/prometheus/client_golang/api/client.go, vendor/github.com/prometheus/client_golang/api/prometheus/v1/api.go, vendor/modules.txt
https://github.com/harvester/harvester/issues/4993
For the first version of this feature, focus on fetching **current alert**.
I think If we fetch too many alerts here, it might be a problem for us debugging because it's too much and not easy to be queried. So, I just fetch **current alert** and format it.
Case 1. Generate support bundle without enabling rancher-monitoring, it should succeed as well, excluding `prometheus-alerts.json`.
Case 2. Generate support bundle with enable rancher-monitoring, there should be a file called `prometheus-alerts.json` in first layer of directory.
<details>
<summary>Sample, it only shows pending and firing state alert</summary>
```js
[
{
"activeAt": "2024-01-23T06:59:00Z",
"Annotations": {
"description": "100% of the rancher/rancher targets in …
```
=> feat: add prometheus alerts in support bundle

package/Dockerfile
Fix CVE vulnerability `SUSE-SU-2024:2302-1`.
Ref longhorn/longhorn#8976
=> Build: upgrade base image to 15.6

pkg/manager/manager.go, pkg/manager/manager_test.go
https://github.com/harvester/harvester/issues/6898
1. Passing a flag decides if set error or not.
2. `progressCount` should increase when getting error in optional phases
=> fix: shouldn't set error in optional phases

cmd/simulator.go, pkg/simulator/apiserver/apiserver.go, pkg/simulator/apiserver/apiserver_test.go, pkg/simulator/crd/crd_test.go, pkg/simulator/objects/apply.go, pkg/simulator/objects/process_node_zips.go, pkg/simulator/objects/progress.go
Related to my SUSE hack week project: https://hackweek.opensuse.org/projects/sbk-simulator-enhancements
Relax the client-side throttling to speed up bundle loading time.
The default rate limiter has Burst set to 10 and QPS set to 5, increasing the number (technically no limitation) to boost the bundle loading time.
I tested loading a customer bundle, the loading time decreased from **46min38s** to **1min20s**.
Todo:
- Add a 5-second sleep before loading speed. This should be good for most case and we can improve this later.
- Observation: the processing speed is around 60~80 objects per second on two bare-metal machines.
- Setting the burst/QPS to 100 should be reasonable.
- Add flags so the values are tuneable.
- CI pass and it looks OK for most tests.
=> Simulator: speed up bundle loading

scripts/build
Ref: longhorn/longhorn#11106
Note: This aligns with the appo image build
=> build: enforce the use of vendor directory

README.md
This can confuse some engineers about the node taints and is worth to be on Known Issues section.
=> doc: adding NoSchedule taint to known issues

pkg/simulator/objects/objects.go
When loading a SB in on macOS, I encountered the following error:
```sh
FATA[0034] Error loading namespacedobjects yaml: control characters are not allowed
```
The issue was caused by `.DS_Store` files interfering with the simulator, as it's not in YAML format and triggered the `control characters are not allowed` error. This PR resolves the issue by filtering out all files that don't have a .yaml suffix when loading objects. It also improves the `GenerateObjects` method by adding a more explicit error message.
=> Fix control characters are not allowed under MacOS

hack/collector-harvester
Related Issue: https://github.com/harvester/harvester/issues/8332
1. While running the command `/sbin/supportconfig -c -m -B supportconfig_test  -i BOOT,DAEMONS,ETC,ISCSI,MEM,MOD,NTP,SMART,DISK,pharvester_plugin_rke2,pharvester_plugin_console`, terminate it on purpose.
2. Run that command again, it'll create different folder name by appending random string. 
3. Then, you can't get the supportconfig in the downloaded support bundle
This case restricts users from getting the supportconfig tarball. Hence, we need to use pre-defined random string the control the folder name.
=> fix: use random string to avoid duplicated scc folder
