pkg/manager/client/discovery.go
pkg/manager/cluster.go

[issue: #19](https://github.com/rancher/support-bundle-kit/issues/19)
[issue: #21](https://github.com/rancher/support-bundle-kit/issues/21)

Resolve resource url and  name conflict

---

pkg/manager/client/discovery.go

[issue: 25](https://github.com/rancher/support-bundle-kit/issues/25)

clean up token and ca.crt information in the secret objects

---

package/Dockerfile

**Related issue**
https://github.com/harvester/harvester/issues/1868

Switch to BCI image

---

hack/collector-harvester

Copy `/var/lib/rancher/rke2/agent/logs/kubelet.log` into support-bundle.

Add kubelet.log

---

hack/collector-sle-micro-rancher

Signed-off-by: Kiefer Chang <kiefer.chang@suse.com>
Related issue: https://github.com/harvester/harvester/issues/2420

Add support for SLE Micro Rancher

---

package/Dockerfile

Signed-off-by: Kiefer Chang <kiefer.chang@suse.com>

Always use latest yq

---

pkg/simulator/objects/apply.go

Signed-off-by: Chin-Ya Huang <chin-ya.huang@suse.com>

fix(simulator): show error when failed to create resource

---

pkg/manager/client/discovery.go

client/discovery: kind value should respect the original case

---

cmd/manager.go
pkg/manager/client/discovery.go
pkg/manager/cluster.go
pkg/manager/collectors/cluster.go
pkg/manager/collectors/common.go
pkg/manager/collectors/default.go
pkg/manager/collectors/harvester.go
pkg/manager/manager.go
pkg/simulator/objects/apply.go

related issues: https://github.com/harvester/harvester/issues/3064
1. generate the support bundle
2. use support-bundle-kit to simulate the environment that the above support bundle described.
3. check the secret data is exists and correct  as following described
- check the file `<SB folder>/yamls/namespaced/fleet-local/v1/secrets.yaml`
- check  the file content should only include the type `rke.cattle.io/machine-plan` by command `grep -nr "  type:"`
- check the `data` items should not be empty

collect plan secret for harvester

---

.drone.yml
Dockerfile.dapper
scripts/validate

ci: add arm64 and s390x support
For https://github.com/rancher/support-bundle-kit/issues/53
Signed-off-by: Yang Chiu <yang.chiu@suse.com>

ci: add arm64 and s390x support

---

.drone.yml

ci: add volume mount to s390x publish steps
Signed-off-by: Yang Chiu <yang.chiu@suse.com>

ci: add volume mount to s390x publish steps

---

scripts/package

build: fix wrong dockerfile configuration for multi-platform
Signed-off-by: Yang Chiu <yang.chiu@suse.com>

build: fix wrong dockerfile configuration for multi-platform

---

.drone.yml

build: fix wrong configuration when publishing tagged image
Signed-off-by: Yang Chiu <yang.chiu@suse.com>

build: fix wrong configuration when publishing tagged image

---

package/Dockerfile

from SLE BCI 15.3 to 15.4
Ref: https://github.com/harvester/harvester/issues/3149, https://github.com/longhorn/longhorn/issues/5107

build(image): bump SLE BCI base image

---

cmd/manager.go
pkg/manager/agent.go
pkg/manager/manager.go

https://github.com/longhorn/longhorn/issues/5467

fix(agent): missing registry secret for air-gapped environment

---

pkg/simulator/objects/apply.go

PR introduces two minor changes to speed up bundle loading when using simulator:
* store gvk lookup in a map to avoid dynamic client lookups
* move default object application to create, and on failure, if object exists just perform a get to attempt status update.
This has improved integration test performance significantly.

speed up loading up objects into bundle

---

hack/collector-harvester
pkg/manager/collectors/harvester.go

Minor tweaks to harvester collectors to fetch the following additional info:
* supportconfig from nodes
* harvester settings not containing sensitive information.
Related to: https://github.com/harvester/harvester/issues/3494

collect harvester settings and supportconfig

---

hack/collector-longhorn

https://github.com/longhorn/longhorn/issues/7121

fix(collector-longhorn): k3s cluster missing kubelet log

---

.drone.yml

The runner doesn't work anymore.

Remove S390x build

---

Dockerfile.dapper
docs/development.md
go.mod
go.sum
vendor/k8s.io/apimachinery/pkg/api/validation/objectmeta.go
vendor/k8s.io/apiserver/pkg/registry/rest/meta.go
vendor/k8s.io/kubernetes/pkg/registry/core/pod/strategy.go
vendor/modules.txt

PR fixes missing vendor changes which are needed to ensure sbk simulator loads original timestamps and log redirection works correctly.

fix missing vendoring changes

---

pkg/simulator/objects/apply.go
pkg/simulator/objects/process_node_zips.go
pkg/simulator/objects/progress.go

Add a simple progress report to indicate support bundle loading progress.
https://github.com/rancher/support-bundle-kit/assets/1691518/0acd33d7-dc5c-4251-85f7-33a5da4ea7a7

Simulator: add a simple progress report

---

.github/workflows/master.yml
.github/workflows/pull-request.yml
.github/workflows/tag.yml
.github/workflows/template-build.yml

Tested in 
- https://github.com/Yu-Jack/support-bundle-kit/actions/runs/8596134282
- https://github.com/Yu-Jack/support-bundle-kit/actions/runs/8596421424
My docker hub in https://hub.docker.com/repository/docker/jk82421/support-bundle-kit/tags
Rancher docker hun in https://hub.docker.com/repository/docker/rancher/support-bundle-kit/tags

ci: add github action

---

.github/workflows/pull-request.yml
.github/workflows/template-build.yml

fix build-args issue
related issue: https://github.com/harvester/harvester/issues/5327

ci: fix arm64

---

.github/workflows/template-build.yml

https://github.com/rancherlabs/eio/issues/2159

ci: use vault to read secret

---

.github/workflows/tag.yml
.github/workflows/template-build.yml

Related issue: https://github.com/rancher/support-bundle-kit/issues/48

ci: publish artifacts to releases

---

.github/workflows/template-build.yml

https://github.com/harvester/security/issues/60

chore: remove untrusted action

---

.github/workflows/template-build.yml

https://github.com/harvester/security/issues/60

chore: add action env

---

hack/collector-longhorn

feat(longhorn): collect proc/mounts and multipath.config

---

pkg/manager/httpserver.go
pkg/manager/manager.go
pkg/manager/types.go

feat(ipv6): add address family support when collecting node bundle

---

go.mod
go.sum
package/Dockerfile
vendor/k8s.io/kubernetes/pkg/apis/core/validation/validation.go
vendor/k8s.io/kubernetes/plugin/pkg/admission/noderestriction/admission.go
vendor/modules.txt

chore: fix CVE issues

---

go.mod
go.sum
vendor/gopkg.in/yaml.v3/parserc.go
vendor/k8s.io/apimachinery/pkg/api/validation/objectmeta.go
vendor/k8s.io/apiserver/pkg/registry/rest/meta.go
vendor/k8s.io/kubernetes/pkg/registry/batch/job/strategy.go
vendor/k8s.io/kubernetes/pkg/registry/core/pod/strategy.go
vendor/k8s.io/kubernetes/plugin/pkg/admission/noderestriction/admission.go
vendor/modules.txt

chore(cve): update vendors

---

hack/collector-longhorn
package/Dockerfile
pkg/manager/agent.go

and processes status using the "ps auxw" command.
ref: longhorn/longhorn#8397

feat(longhorn): collect proc/pid/status
